# Generated by Django 4.2.2 on 2023-08-11 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_catagory_product_image_product_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='catagory',
            new_name='category',
        ),
    ]
