# Generated by Django 4.2.2 on 2023-08-16 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_rename_catagory_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=200)),
                ('email', models.CharField(default='', max_length=200)),
                ('desc', models.CharField(default='', max_length=200)),
                ('phone', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
