# Generated by Django 4.2.2 on 2023-08-18 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='Phone',
            field=models.CharField(default='', max_length=20),
        ),
    ]
