# Generated by Django 4.2.6 on 2024-01-13 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_product_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='MRP',
            field=models.IntegerField(default=0),
        ),
    ]
