# Generated by Django 4.2.6 on 2024-01-13 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_product_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Discount',
        ),
    ]
