# Generated by Django 4.2.6 on 2024-01-13 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_remove_product_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sub_catagory',
            new_name='sub_category',
        ),
    ]
